### ISSUE TITLE
make the grid kinda responsive

### ISSUE THREAD

**Issue by benjamin-lewandowski** [fimion/css-trickz#7]
Maybe something like `grid-template-columns: repeat( auto-fit, minmax(60ch, 1fr) );` would be a good replacement for your `grid-auto-columns: 1fr 1fr 1fr;` so the "design" is also viewable on smaller screens.

**Comment by fimion** [comment]
I like this. I think I'm going to go with `45ch` because I'm okay with the articles getting a bit smaller.
